### ISSUE TITLE
[QUESTION] Why is it not allow to copy files to a destination folder?

### ISSUE THREAD

**Issue by wardmatc** [npm/move-file#8]
# What / Why
Currently, the move-file forces me to set a destination file. I would like to know if there is a reason behind the fact that setting a destination path=existing folder , does not move files inside?

## Where
I would like to use it as "move-file test.file /directory/" but it forces me to use "move-file test.file /directory/test.file"
It may look trivial but when using wildcards that restriction became a problem for me "move-file *.txt /directory/"

**Comment by wraithgar** [comment]
The reason is that this is a single-use lib to replace [fs-rename](https://nodejs.org/api/fs.html#fs_fs_rename_oldpath_newpath_callback) in a way that works across devices.  It is for moving a single file, nothing more.
